const purpleColor = "#655a7c";
const orangeColor = "#fc814a";

export const baseTheme = {
    breakpoints: {
        xs: "0",
        sm: "576px",
        md: "768px",
        lg: "992px",
        xl: "1200px",
        xxl: "1400px",
    },
    colors: {
        inherit: "inherit",
        primary: purpleColor,
        secondary: orangeColor,
        blue: "#afc1d6",
        greyDarkest: "#3a3238",
        greyDarken: "#4b5358",
        greyDark: "#727072",
        grey: "#96939b",
        greyLight: "#d1d1d1",
        greyLighten: "#e8e8e8",
        greyLightest: "#f8f8f8",
        greenDarken: "#305959",
        green: "#2aa3a3",
        greenLighten: "#aee8e9",
        greenLightest: "#e4f7f8",
        orangeDarken: "#853117",
        orangeDark: "#e25b30",
        orange: orangeColor,
        orangeLight: "#fccba4",
        orangeLighten: "#ffe7d4",
        purpleDark: "#453545",
        purpleDarker: "#372a37",
        purple: purpleColor,
        purpleLight: "#9078a2",
        purpleLighten: "#b1a0bd",
        purpleLightest: "#efdefa",
        redDarken: "#7d332c",
        red: "#d63124",
        redLighten: "#efada7",
        redLightest: "#f7d6d3",
        white: "#ffffff",
        yellow: "lightyellow",
    },
    durations: {
        fast: "50ms",
        normal: "100ms",
        slow: "150ms",
    },
    fonts: {
        inherit: "inherit",
        logo: "Bree Serif, Helvetica, Arial, sans-serif",
        normal: "Roboto, Helvetica, Arial, sans-serif",
    },
    fontSizes: {
        inherit: "inherit",
        xxs: "1rem",
        xs: "1.2rem",
        sm: "1.4rem",
        md: "1.6rem",
        lg: "1.8rem",
        xl: "2rem",
        xxl: "2.2rem",
    },
    zIndex: {
        tooltip: 11,
        modal: 10,
        navbar: 9,
    },
} as const;
