spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_USERS_HOST}:${DB_USERS_PORT}/${DB_USERS_NAME}
        username: ${DB_USERS_USER}
        password: ${DB_USERS_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: create
        generate-ddl: true
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: ${API_USERS_PORT:3001}

api-users:
    prefix: /${API_USERS_PREFIX:api}
    resource: ${API_USERS_RESOURCE:users}
