spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_USERS_HOST}:${DB_USERS_PORT}/${DB_USERS_NAME}
        username: ${DB_USERS_USER}
        password: ${DB_USERS_PASSWORD}
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false

server:
    port: ${API_USERS_PORT:3001}

api-users:
    prefix: ${API_USERS_PREFIX:api}
    resource: ${API_USERS_RESOURCE:users}

---

spring:
    config:
        activate:
            on-profile: dev
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true

---

spring:
    config:
        activate:
            on-profile: prod
