spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_POSTS_HOST}:${DB_POSTS_PORT}/${DB_POSTS_NAME}
        username: ${DB_POSTS_USER}
        password: ${DB_POSTS_PASSWORD}
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false

server:
    port: ${API_POSTS_PORT:3002}

api-posts:
    base-url: http://${API_POSTS_HOST}:${API_POSTS_PORT}
    prefix: ${API_POSTS_PREFIX:api}
    resource: ${API_POSTS_RESOURCE:posts}

api-users:
    base-url: http://${API_USERS_HOST}:${API_USERS_PORT}
    prefix: ${API_USERS_PREFIX:api}
    resource: ${API_USERS_RESOURCE:users}

---

spring:
    config:
        activate:
            on-profile: dev
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true

---

spring:
    config:
        activate:
            on-profile: prod
