version: "3.9"

services:
    api-gateway:
        container_name: geek-regime-api-gateway_dev
        ports:
            - ${API_GATEWAY_PORT_DEBUG}:${API_GATEWAY_PORT_DEBUG}
        build:
            context: ../api-gateway
            dockerfile: $PWD/builder/api-gateway/Dockerfile.development
        command: npm run start:debug
        volumes:
            - ../api-gateway:/app
            # - /app/node_modules

    api-aggregator:
        container_name: geek-regime-api-aggregator_dev
        command: mvn spring-boot:run -D spring-boot.run.profiles=dev
        volumes:
            - ../api-aggregator:/app

    api-users:
        container_name: geek-regime-api-users_dev
        command: mvn spring-boot:run -D spring-boot.run.profiles=dev,seed-fake-data
        volumes:
            - ../api-users:/app

    api-posts:
        container_name: geek-regime-api-posts_dev
        command: mvn spring-boot:run -D spring-boot.run.profiles=dev,seed-fake-data
        volumes:
            - ../api-posts:/app

    db-users:
        container_name: geek-regime-db-users_dev
        volumes:
            - db-users-data_dev:${DB_USERS_DATA_PATH}

    db-posts:
        container_name: geek-regime-db-posts_dev
        volumes:
            - db-posts-data_dev:${DB_POSTS_DATA_PATH}

    client-web:
        container_name: geek-regime-client-web_dev
        build:
            context: ../client-web
            dockerfile: $PWD/builder/client-web/Dockerfile.development
        command: npm start
        volumes:
            - ../client-web:/app
            # - /app/node_modules
        tty: true

volumes:
    db-posts-data_dev:
    db-users-data_dev:
        driver: local

# [1] Must correspond to an existing tag from the Docker repository:
# https://hub.docker.com/repository/docker/eggziom/geek-regime-api-commons
