version: "3.9"

services:
    api-gateway:
        container_name: geek-regime-api-gateway_prod
        build:
            context: ../api-gateway
            dockerfile: $PWD/builder/api-gateway/Dockerfile.production
        command: npm start
        volumes:
            - ../client-web/dist:/public

    api-users:
        volumes:
            - api-users-search-data_prod:${API_USERS_SEARCH_DATA_PATH}

volumes:
    api-posts-search-data_prod:
    api-users-search-data_prod:
        driver: local
