openapi: 3.1.0
info:
  title: Schema components
  version: v1
components:
  schemas:
    # User
    UserPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/UserResponse"
    UserResponse:
      type: object
      required: [ id, email, slug, createdAt, updatedAt, lastSeenAt, details ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        email:
          type: string
          format: email
        slug:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        lastSeenAt:
          type: string
          format: date-time
        details:
          type: object
          $ref: "#/components/schemas/UserDetails"
    UserDetails:
      type: object
      required: [ name, image, gender, createdAt, updatedAt ]
      properties:
        name:
          type: string
        description:
          type: string
        about:
          type: string
        image:
          type: string
        gender:
          type: string
          enum: [ "MALE", "FEMALE" ]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateUserRequest:
      type: object
      required: [ email, details ]
      properties:
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
        details:
          type: object
          $ref: "#/components/schemas/CreateUserDetails"
    CreateUserDetails:
      type: object
      required: [ name ]
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        about:
          type: string
          minLength: 1
        image:
          type: string
          minLength: 1
        gender:
          type: string
          enum: [ "MALE", "FEMALE" ]
    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        oldPassword:
          type: string
          minLength: 1
        newPassword:
          type: string
          minLength: 1
        details:
          type: object
          $ref: "#/components/schemas/UpdateUserDetails"
    UpdateUserDetails:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        about:
          type: string
          minLength: 1
        image:
          type: string
          minLength: 1
        gender:
          type: string
          enum: [ "MALE", "FEMALE" ]
    AuthenticateRequest:
      type: object
      required: [ email, password ]
      properties:
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
    # Post
    PostPreviewPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/PostPreviewResponse"
    BasePostPreviewPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/BasePostPreviewResponse"
    PostDetailsResponse:
      type: object
      required: [ id, title, excerpt, slug, createdAt, updatedAt, body, author ]
      allOf:
        - $ref: "#/components/schemas/PostResponseBase"
        - $ref: "#/components/schemas/HasAuthor"
        - $ref: "#/components/schemas/HasBody"
        - $ref: "#/components/schemas/HasVotes"
    BasePostDetailsResponse: # DTO from base service containing scalar reference ID fields (foreign keys)
      type: object
      required: [ id, title, excerpt, slug, createdAt, updatedAt, authorId, spaceId, body ]
      allOf:
        - $ref: "#/components/schemas/PostResponseBase"
        - $ref: "#/components/schemas/PostRefs"
        - $ref: "#/components/schemas/HasBody"
        - $ref: "#/components/schemas/HasVotes"
    PostPreviewResponse: # DTO from aggregator service containing populated reference fields
      type: object
      required: [ id, title, excerpt, slug, createdAt, updatedAt, author ]
      allOf:
        - $ref: "#/components/schemas/PostResponseBase"
        - $ref: "#/components/schemas/HasAuthor"
    BasePostPreviewResponse:
      type: object
      required: [ id, title, excerpt, slug, createdAt, updatedAt, authorId, spaceId ]
      allOf:
        - $ref: "#/components/schemas/PostResponseBase"
        - $ref: "#/components/schemas/PostRefs"
    CreatePostRequest:
      type: object
      required: [ authorId, spaceId, title, body ]
      properties:
        authorId:
          type: integer
          format: int64
          minimum: 1
        spaceId:
          type: integer
          format: int64
          minimum: 1
        title:
          type: string
          minLength: 1
        body:
          type: string
          minLength: 1
    UpdatePostRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        body:
          type: string
          minLength: 1
    VoteOnPostRequest:
      type: object
      required: [ value ]
      properties:
        value:
          type: integer
          format: int64
          minimum: -1
          maximum: 1
    PostResponseBase: # fields shared by all post response DTOs
      type: object
      required: [ id, title, excerpt, slug, createdAt, updatedAt ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        title:
          type: string
        excerpt:
          type: string
        slug:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        meta:
          type: object
          required: [ id, rating, viewCount, commentCount ]
          properties:
            id:
              type: integer
              format: int64
              minimum: 1
            rating:
              type: integer
              format: int64
            viewCount:
              type: integer
              format: int64
            commentCount:
              type: integer
              format: int64
    PostVote:
      type: object
      required: [ id, userId, value ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        userId:
          type: integer
          format: int64
          minimum: 1
        value:
          type: integer
          format: int64
    PostRefs:
      type: object
      required: [ authorId, spaceId ]
      properties:
        authorId:
          type: integer
          format: int64
          minimum: 1
        spaceId:
          type: integer
          format: int64
          minimum: 1
    # Post Comment
    PostCommentPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/PostCommentResponse"
    BasePostCommentPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/BasePostCommentResponse"
    BasePostCommentResponse: # DTO from base service containing scalar reference ID fields (foreign keys)
      type: object
      required: [ id, body, createdAt, updatedAt, authorId, postId ]
      allOf:
        - $ref: "#/components/schemas/PostCommentResponseBase"
        - $ref: "#/components/schemas/PostCommentRefs"
    PostCommentResponse: # DTO from aggregator service containing populated reference fields
      type: object
      required: [ id, author, body, createdAt, updatedAt ]
      allOf:
        - $ref: "#/components/schemas/PostCommentResponseBase"
        - $ref: "#/components/schemas/HasAuthor"
    CreatePostCommentRequest:
      type: object
      required: [ authorId, postId, body ]
      properties:
        authorId:
          type: integer
          format: int64
          minimum: 1
        postId:
          type: integer
          format: int64
          minimum: 1
        body:
          type: string
          minLength: 1
    UpdatePostCommentRequest:
      type: object
      properties:
        body:
          type: string
          minLength: 1
    PostCommentResponseBase: # fields shared by all post comment response DTOs
      type: object
      required: [ id, body, createdAt, updatedAt ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        body:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PostCommentRefs:
      type: object
      required: [ authorId, postId ]
      properties:
        authorId:
          type: integer
          format: int64
          minimum: 1
        postId:
          type: integer
          format: int64
          minimum: 1
    # Common
    Page:
      type: object
      required: [ size, totalElements ]
      properties:
        size:
          type: integer
          format: int32
          minimum: 1
        totalElements:
          type: integer
          format: int64
          minimum: 0
    IdResponse:
      type: object
      required: [ id ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
    HasBody:
      type: object
      required: [ body ]
      properties:
        body:
          type: string
    HasVotes:
      type: object
      required: [ id, userId, value ]
      properties:
        votes:
          type: array
          items:
            $ref: "#/components/schemas/PostVote"
    HasAuthor:
      type: object
      required: [ author ]
      properties:
        author:
          type: object
          $ref: "#/components/schemas/UserResponse"
