openapi: 3.1.0
info:
  title: Common schema components
  version: v1
components:
  schemas:
    Page:
      type: object
      required: [ size, totalElements ]
      properties:
        size:
          type: integer
          format: int32
          minimum: 1
        totalElements:
          type: integer
          format: int64
          minimum: 0
    PagePeriod:
      type: string
      enum: [ "DAY", "WEEK", "MONTH", "YEAR", "OVERALL" ]
    IdResponse:
      type: object
      required: [ id ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
    ErrorCode:
      type: string
      enum: [ "ABSENT", "ALREADY_EXISTS", "ALREADY_REMOVED", "INTEGRATION_ERROR", "INVALID", "MISMATCH" ]
    ApiErrorDetail:
      type: object
      required: [ code, field ]
      properties:
        code:
          type: string
        field:
          type: string
    ApiError:
      type: object
      required: [ status, path, message, details, timestamp ]
      properties:
        status:
          type: integer
        path:
          type: string
        resource:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            $ref: "#/components/schemas/ApiErrorDetail"
        timestamp:
          type: string
        trace:
          type: string
