openapi: 3.1.0
info:
  title: Post comment schema components
  version: v1
components:
  schemas:
    # Response DTOs from base service containing scalar reference ID fields (foreign keys):
    BasePostCommentPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/BasePostCommentResponse"
    BasePostCommentResponse:
      type: object
      required: [ id, createdAt, updatedAt, authorId, postId, descendantCount ]
      allOf:
        - $ref: "#/components/schemas/PostCommentResponseBase"
        - $ref: "#/components/schemas/PostCommentRefs"
        - type: object
          properties:
            descendantCount:
              type: integer
              format: int64
              minimum: 0
    BasePostCommentTreeResponse:
      type: object
      required: [ id, createdAt, updatedAt, authorId, postId, replies ]
      allOf:
        - $ref: "#/components/schemas/PostCommentResponseBase"
        - $ref: "#/components/schemas/PostCommentRefs"
        - type: object
          properties:
            replies:
              type: array
              items:
                $ref: "#/components/schemas/BasePostCommentTreeResponse"
    # Response DTOs from aggregator service containing populated reference fields:
    PostCommentPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/PostCommentResponse"
    PostCommentResponse:
      type: object
      required: [ id, createdAt, updatedAt, author, postId, descendantCount ]
      allOf:
        - $ref: "#/components/schemas/PostCommentResponseBase"
        - type: object
          properties:
            author:
              $ref: "#/components/schemas/UserResponse"
            descendantCount:
              type: integer
              format: int64
              minimum: 0
    PostCommentTreeResponse:
      type: object
      required: [ id, createdAt, updatedAt, author, postId, replies ]
      allOf:
        - $ref: "#/components/schemas/PostCommentResponseBase"
        - type: object
          properties:
            author:
              $ref: "#/components/schemas/UserResponse"
            replies:
              type: array
              items:
                $ref: "#/components/schemas/PostCommentTreeResponse"
    # Request DTOs:
    CreatePostCommentRequest:
      type: object
      required: [ authorId, postId, body ]
      properties:
        authorId:
          type: integer
          format: int64
          minimum: 1
        postId:
          type: integer
          format: int64
          minimum: 1
        parentId:
          type: integer
          format: int64
          minimum: 1
        body:
          type: string
          minLength: 1
    UpdatePostCommentRequest:
      type: object
      properties:
        body:
          type: string
          minLength: 1
    # Shared fields:
    PostCommentResponseBase: # fields shared by all post comment response DTOs
      type: object
      required: [ id, createdAt, updatedAt ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        body:
          type: string
        isDeleted:
          type: boolean
        postId:
          type: integer
          format: int64
          minimum: 1
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PostCommentRefs: # scalar reference ID fields (foreign keys)
      type: object
      required: [ authorId, postId ]
      properties:
        authorId:
          type: integer
          format: int64
          minimum: 1
        postId:
          type: integer
          format: int64
          minimum: 1
    # Refs:
    Page:
      type: Page
      $ref: "./common.yml#/components/schemas/Page"
    UserResponse:
      type: UserResponse
      $ref: "./user.yml#/components/schemas/UserResponse"
