openapi: 3.1.0
info:
  title: Space schema components
  version: v1
components:
  schemas:
    # Response DTOs from base service containing scalar reference ID fields (foreign keys):
    SpacePageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/SpaceResponse"
    # Response DTOs from aggregator service containing populated reference fields:
    SpaceResponse:
      type: object
      required: [ id,  title, slug, createdAt, updatedAt ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        title:
          type: string
        description:
          type: string
        slug:
          type: string
        isOfficial:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    # Request DTOs:
    SaveSpaceRequest:
      type: object
      required: [ title ]
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
    # Refs:
    Page:
      type: Page
      $ref: "./common.yml#/components/schemas/Page"
