openapi: 3.1.0
info:
  title: User schema components
  version: v1
components:
  schemas:
    # Response DTOs:
    UserPageResponse:
      required: [ content, size, totalElements ]
      allOf:
        - $ref: "#/components/schemas/Page"
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/UserResponse"
    UserResponse:
      type: object
      required: [ id, email, slug, createdAt, updatedAt, lastSeenAt, details ]
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        email:
          type: string
          format: email
        slug:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        lastSeenAt:
          type: string
          format: date-time
        details:
          type: object
          $ref: "#/components/schemas/UserDetails"
    UserDetails:
      type: object
      required: [ name, image, gender, createdAt, updatedAt ]
      properties:
        name:
          type: string
        description:
          type: string
        about:
          type: string
        image:
          type: string
        gender:
          type: string
          enum: [ "MALE", "FEMALE" ]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    # Request DTOs:
    CreateUserRequest:
      type: object
      required: [ email, details ]
      properties:
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
        details:
          type: object
          $ref: "#/components/schemas/CreateUserDetails"
    CreateUserDetails:
      type: object
      required: [ name ]
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        about:
          type: string
          minLength: 1
        image:
          type: string
          minLength: 1
        gender:
          type: string
          enum: [ "MALE", "FEMALE" ]
    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        oldPassword:
          type: string
          minLength: 1
        newPassword:
          type: string
          minLength: 1
        details:
          type: object
          $ref: "#/components/schemas/UpdateUserDetails"
    UpdateUserDetails:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        about:
          type: string
          minLength: 1
        image:
          type: string
          minLength: 1
        gender:
          type: string
          enum: [ "MALE", "FEMALE" ]
    AuthenticateRequest:
      type: object
      required: [ email, password ]
      properties:
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          minLength: 1
    # Refs:
    Page:
      type: Page
