spring:
    config:
        import: optional:file:.env[.properties]
    profiles:
        active: prod

server:
    port: ${API_AGGREGATOR_PORT:3001}
    servlet:
        context-path: /api

api-posts:
    base-url: http://${API_POSTS_HOST}:${API_POSTS_PORT}

api-users:
    base-url: http://${API_USERS_HOST}:${API_USERS_PORT}

---

spring:
    config:
        activate:
            on-profile: dev

---

spring:
    config:
        activate:
            on-profile: prod

server:
    error:
        include-stacktrace: on_param
