spring:
    config:
        import: optional:file:.env[.properties]
    profiles:
        active: prod

server:
    port: ${API_AGGREGATOR_PORT:3001}

api-posts:
    base-url: http://${API_POSTS_HOST}:${API_POSTS_PORT}
    prefix: ${API_POSTS_PREFIX:api}
    resource: ${API_POSTS_RESOURCE:posts}

api-users:
    base-url: http://${API_USERS_HOST}:${API_USERS_PORT}
    prefix: ${API_USERS_PREFIX:api}
    resource: ${API_USERS_RESOURCE:users}

---

spring:
    config:
        activate:
            on-profile: dev

---

spring:
    config:
        activate:
            on-profile: prod

server:
    error:
        include-stacktrace: on_param
