openapi: 3.1.0
info:
  title: Parameter components
  version: v1
components:
  parameters:
    idOrSlug:
      name: idOrSlug
      description: The ID of the slug of the user
      in: path
      schema:
        type: string
    id:
      name: id
      description: The ID of an entity
      in: path
      schema:
        type: integer
        format: int64
    email:
      name: email
      description: The email of the user
      in: path
      schema:
        type: string
        format: email
    searchIn:
      name: searchIn
      description: The list of fields to search the text in
      in: query
      schema:
        type: array
        items:
          type: string
        examples:
          - "title"
          - "title,excerpt"
    text:
      name: text
      description: The text to search
      in: query
      schema:
        type: string
        example: "Something I wanna find"
