openapi: 3.1.0
info:
  version: v1
  title: api-spaces
servers:
  - url: http://localhost:3003/api/v1
paths:
  /spaces:
    get:
      summary: Find all spaces
      operationId: findAllSpaces
      tags:
        - space
      x-spring-paginated: true
      parameters:
        - $ref: "./parameters-v1.yml#/components/parameters/searchIn"
        - $ref: "./parameters-v1.yml#/components/parameters/text"
      responses:
        200:
          description: A list of spaces
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpacePageResponse"
    put:
      summary: Save spaces
      description: Saves the list of provided spaces. If there's already a space with the same title, doesn't overwrite it.
      operationId: saveSpaces
      tags:
        - space
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SaveSpaceRequest"
      responses:
        200:
          description: The created post
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SpaceResponse"
  /spaces/{slug}:
    get:
      summary: Find space by slug
      operationId: findSpaceBySlug
      tags:
        - space
      parameters:
        - $ref: "./parameters-v1.yml#/components/parameters/slug"
      responses:
        200:
          description: The space
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpaceResponse"
  /spaces/{id}:
    delete:
      summary: Remove space by ID
      operationId: removeSpaceById
      tags:
        - space
      parameters:
        - $ref: "./parameters-v1.yml#/components/parameters/id"
      responses:
        200:
          description: The ID of the removed space
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IdResponse"
components:
  # Schemas imported from api-commons
  schemas:
    SpacePageResponse:
      type: SpacePageResponse
    SpaceResponse:
      type: SpaceResponse
    SaveSpaceRequest:
      type: SaveSpaceRequest
    IdResponse:
      type: IdResponse
