openapi: 3.1.0
info:
  title: Schema components
  version: v1
components:
  schemas:
    CreatePostRequest:
      type: object
      required: [ authorId, spaceId, title, body ]
      properties:
        authorId:
          type: integer
          format: int64
          min: 1
        spaceId:
          type: integer
          format: int64
          min: 1
        title:
          type: string
          minLength: 1
        body:
          type: string
          minLength: 1
    UpdatePostRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        body:
          type: string
          minLength: 1
