spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_POSTS_HOST}:${DB_POSTS_PORT}/${DB_POSTS_NAME}
        username: ${DB_POSTS_USER}
        password: ${DB_POSTS_PASSWORD}
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    profiles:
        active: prod

server:
    port: ${API_POSTS_PORT:3002}
    servlet:
        context-path: /${API_POSTS_PREFIX}

api-posts:
    base-url: http://${API_POSTS_HOST}:${API_POSTS_PORT}
    prefix: ${API_POSTS_PREFIX:api}
    resource: ${API_POSTS_RESOURCE:posts}

api-users:
    resource: ${API_USERS_RESOURCE:users}

---

spring:
    config:
        activate:
            on-profile: dev
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                hbm2ddl:
                    import_files: import.sql
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        show-sql: true
    sql:
        init:
            mode: always

---

spring:
    config:
        activate:
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false

server:
    error:
        include-stacktrace: on_param
