spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_POSTS_HOST}:${DB_POSTS_PORT}/${DB_POSTS_NAME}
        username: ${DB_POSTS_USER}
        password: ${DB_POSTS_PASSWORD}
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                search:
                    backend:
                        lucene_version: 8.11.1
                        type: lucene
    profiles:
        active: prod

server:
    port: ${API_POSTS_PORT:3002}

api-posts:
    base-url: http://${API_POSTS_HOST}:${API_POSTS_PORT}
    prefix: ${API_POSTS_PREFIX:api}
    resource: ${API_POSTS_RESOURCE:posts}

---

spring:
    config:
        activate:
            on-profile: dev
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                hbm2ddl:
                    import_files: import.sql
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
                search:
                    backend:
                        directory.type: local-heap
        show-sql: true
    sql:
        init:
            mode: always

---

spring:
    config:
        activate:
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            search:
                backend:
                    directory.root: ${API_POSTS_SEARCH_DATA_PATH:data/index}
        show-sql: false

server:
    error:
        include-stacktrace: on_param
