spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_POSTS_HOST}:${DB_POSTS_PORT}/${DB_POSTS_NAME}
        username: ${DB_POSTS_USER}
        password: ${DB_POSTS_PASSWORD}
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    profiles:
        active: prod

server:
    port: ${API_POSTS_PORT:3003}
    servlet:
        context-path: /api

api-posts:
    base-url: http://${API_POSTS_HOST}:${API_POSTS_PORT}

---

spring:
    config:
        activate:
            on-profile: dev
    jpa:
        properties:
            format_sql: true
        show-sql: true

---

spring:
    config:
        activate:
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false

server:
    error:
        include-stacktrace: on_param

---

spring:
    config:
        activate:
            on-profile: seed-fake-data
    jpa:
        hibernate:
            ddl-auto: create

api-posts:
    fake-post-count: 200
    fake-user-count: 80 # it's less in api-users; we simulate deleted authors here

---

spring:
    config:
        activate:
            on-profile: seed-stub-data
    jpa:
        properties:
            hibernate:
                ddl-auto: create
                hbm2ddl:
                    import_files: stub-data.sql
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    sql:
        init:
            mode: always
