name: CD

on:
    push:
        branches: [ production ]

jobs:
    test:
        name: "Test client-web: \"${{ github.event.head_commit.message }}\""
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Test
              run: cd client-web && npm ci && npm run test
