FROM node:18.3.0-alpine as client-build

RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
COPY package-lock.json /app
RUN npm ci --quiet
COPY . /app
RUN npm run build

FROM nginx:1.29.0-alpine

COPY configs/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=client-build /app/dist /usr/share/nginx/html
